= Dotfiles

Just my dotfiles and tools.

== 0. Getting started

=== Prerequisite(s)

* https://git-scm.com[git]
* https://www.gnu.org/software/stow[GNU stow]

=== Installation

[source,shell]
----
# Via SSH
git clone git@github.com:vnea/dotfiles.git ~/dotfiles

# Or via HTTP
git clone https://github.com/vnea/dotfiles.git ~/dotfiles

----

:sectnums:

== Bash aliases
:sectnums!:

=== Installation

In your `.bashrc` or `.zshrc`, add:

[source,bash]
----
##############################
# Load aliases
##############################
for f in $(find ~/dotfiles/aliases -maxdepth 1 -name "*.sh"); do source $f; done

----

Then, reload the configuration:

[source,shell]
----
# For Bash
source .bashrc

# For Zsh
source .zshrc
----

:sectnums:

== Neovim
:sectnums!:

=== Prerequisite(s)

* https://neovim.io[Neovim] &gt;= v0.9

=== Installation

[source,shell]
----
rm -rf ~/.config/nvim && stow nvim
----

:sectnums:

== tmux
:sectnums!:

=== Prerequisite(s)

* https://github.com/tmux/tmux[tmux] &gt;= v3.2

=== Installation

[source,shell]
----
# tmux
rm -rf ~/.tmux.conf ~/.config/tmux && stow tmux

# Install tmux plugins
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
tmux
# Press "CTRL-Q then I", wait for installation and restart tmux
----

:sectnums:

== Git
:sectnums!:

=== Prerequisite(s)

* https://git-scm.com[git]
* https://github.com/dandavison/delta[delta]
* https://github.com/so-fancy/diff-so-fancy[diff-so-fancy]
* (optional) ansible-vault-merge:
.. Download it https://raw.githubusercontent.com/building5/ansible-vault-tools/master/ansible-vault-merge.sh[here]
and name it `ansible-vault-merge`.
.. Check that script is not malicious before continuing.
.. Run: `chmod +x ansible-vault-merge`.
.. Run: `sudo mv ansible-vault-merge /usr/local/bin`.

=== Installation

[source,shell]
----
rm -f ~/.gitconfig
git config --global user.name "User name"
git config --global user.email "email"

cat <<EOT >> ~/.gitconfig

[include]
    path = dotfiles/git/.gitconfig

EOT
----

:sectnums:

== i3
:sectnums!:

=== Prerequisite(s)

* https://i3wm.org[i3wm]
* Betterlockscreen (see section <<betterlockscreen>>)
* https://github.com/polybar/polybar[Polybar]
* https://archlinux.org/packages/community/any/ttf-noto-nerd[ttf-noto-nerd]
* https://github.com/dunst-project/dunst[Dunst] (for Pomodoro Polybar text notification, see section <<dunst>>)
* https://github.com/PapirusDevelopmentTeam/papirus-icon-theme[Papirus icon them]
* https://sox.sourceforge.net/[Sox] (for Pomodoro Polybar sound notification)
* https://feh.finalrewind.org[feh]
* https://github.com/yshui/picom[Picom]
* https://github.com/haikarainen/light[Light]

=== Installation

[source,shell]
----
# i3
rm -rf ~/.config/i3 && stow i3

# picom
rm -rf ~/.config/picom && stow picom

# light
sudo gpasswd -a $USER video
# Reboot computer
----

:sectnums:

== rofi
:sectnums!:

=== Prerequisite(s)

* https://github.com/davatorium/rofi[rofi]
* https://github.com/adi1090x/rofi[rofi-themes]

=== Installation

[source,shell]
----
rm -rf ~/.config/rofi/config.rasi && stow rofi
----

:sectnums:

== thefuck
:sectnums!:

=== Installation

[source,shell]
----
rm -rf ~/.config/thefuck && stow thefuck
----

:sectnums:

== GTK
:sectnums!:

=== Installation

[source,shell]
----
rm -rf ~/.config/gtk-3.0 && stow gtk
----

:sectnums:

== Dunst [[dunst]]
:sectnums!:

=== Installation

[source,shell]
----
rm -rf ~/.config/dunst && stow dunst
----

:sectnums:

== Zsh + Oh My Zsh + Powerlevel10k
:sectnums!:

=== Prerequisite(s)

* https://wiki.archlinux.org/title/zsh[Zsh]
* https://ohmyz.sh/[Oh My Zsh]
* https://github.com/romkatv/powerlevel10k[Powerlevel10k]

=== Installation

[source,shell]
----
rm -f ~/.p10k.zsh && stow p10k
rm -f ~/.zshrc && stow zsh

# Reboot the Terminal
----

:sectnums:

== Betterlockscreen [[betterlockscreen]]
:sectnums!:

Link: https://github.com/betterlockscreen/betterlockscreen

=== Prerequisite(s)

* https://github.com/Raymo111/i3lock-color[i3lock-color]

=== Generate cache

[source,shell]
----
betterlockscreen --update ~/.config/i3/images/lockscreen.jpg --fx blur
----

=== Lockscreen after sleep/suspend

[source,shell]
----
systemctl enable betterlockscreen@$USER
----

:sectnums:

== Alacritty
:sectnums!:

Link: https://github.com/alacritty/alacritty

=== Installation

[source,shell]
----
rm -rf ~/.config/alacritty && stow alacritty
----

:sectnums:

== Flameshot
:sectnums!:

Link: https://flameshot.org/

=== Installation

[source,shell]
----
rm -rf ~/.config/flameshot && stow flameshot
----

:sectnums:

== Systemd services & timers
:sectnums!:

=== Notify low battery

Inspired from: https://life-prog.com/tech/alert-on-low-battery-in-i3

[source,shell]
----
sudo ln -s ~/dotfiles/systemd/user/notify-low-battery /usr/local/bin/notify-low-battery
ln -s ~/dotfiles/systemd/user/notify-low-battery.service ~/.config/systemd/user/notify-low-battery.service
ln -s ~/dotfiles/systemd/user/notify-low-battery.timer ~/.config/systemd/user/notify-low-battery.timer
systemctl --user daemon-reload
systemctl --user start notify-low-battery.service
systemctl --user enable notify-low-battery.timer
systemctl --user start notify-low-battery.timer
----

:sectnums:

== asdf
:sectnums!:

Link: https://asdf-vm.com/

=== Installation

[source,shell]
----
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf plugin-add terragrunt https://github.com/lotia/asdf-terragrunt
asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
asdf plugin-add java https://github.com/halcyon/asdf-java.git
asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git

rm -f ~/.asdfrc && stow asdf
----

== Lazygit
:sectnums!:

Link: https://github.com/jesseduffield/lazygit

=== Installation

[source,shell]
----
# Linux
rm -rf ~/.config/lazygit && stow lazygit

# Mac OS
rm ~/Library/Application\ Support/lazygit/config.yml && ln -s ~/dotfiles/lazygit/.config/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
----

:sectnums:

== Aerospace
:sectnums!:

Link: https://github.com/nikitabobko/AeroSpace

=== Installation

[source,shell]
----
rm -rf ~/.config/aerospace && stow aerospace
----

:sectnums:

== Karabiner
:sectnums!:

Link: https://karabiner-elements.pqrs.org/

=== Installation

[source,shell]
----
rm -rf ~/.config/karabiner && stow karabiner
----

== k9s
:sectnums!:

Link:
  - https://github.com/derailed/k9s
  - https://github.com/derailed/k9s/tree/master/skins (skins)

=== Installation

[source,shell]
----
# Linux
rm -rf ~/.config/k9s && stow k9s

# Mac OS
rm -rf ~/Library/Application\ Support/k9s && ln -s ~/dotfiles/k9s/.config/k9s ~/Library/Application\ Support/k9s
----

:sectnums:
